### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Client.Settings.MagicPackageSettings
  commentId: T:ToSic.Cre8magic.Client.Settings.MagicPackageSettings
  id: MagicPackageSettings
  parent: ToSic.Cre8magic.Client.Settings
  children:
  - ToSic.Cre8magic.Client.Settings.MagicPackageSettings.Defaults
  - ToSic.Cre8magic.Client.Settings.MagicPackageSettings.PackageName
  - ToSic.Cre8magic.Client.Settings.MagicPackageSettings.SettingsJsonFile
  - ToSic.Cre8magic.Client.Settings.MagicPackageSettings.Url
  - ToSic.Cre8magic.Client.Settings.MagicPackageSettings.WwwRoot
  langs:
  - csharp
  - vb
  name: MagicPackageSettings
  nameWithType: MagicPackageSettings
  fullName: ToSic.Cre8magic.Client.Settings.MagicPackageSettings
  type: Class
  source:
    remote:
      path: ToSic.Cre8magic.Client/Settings/MagicPackageSettings.cs
      branch: feature/cre8magic-tests
      repo: https://github.com/2sic/cre8magic.git
    id: MagicPackageSettings
    path: ../ToSic.Cre8magic.Client/Settings/MagicPackageSettings.cs
    startLine: 7
  assemblies:
  - ToSic.Cre8Magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Client.Settings
  summary: >-
    Settings for a Theme Package.


    Contains semi-constants like location of assets and configuration for various parts like CSS.
  example: []
  syntax:
    content: public class MagicPackageSettings
    content.vb: Public Class MagicPackageSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.Defaults
  commentId: P:ToSic.Cre8magic.Client.Settings.MagicPackageSettings.Defaults
  id: Defaults
  parent: ToSic.Cre8magic.Client.Settings.MagicPackageSettings
  langs:
  - csharp
  - vb
  name: Defaults
  nameWithType: MagicPackageSettings.Defaults
  fullName: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.Defaults
  type: Property
  source:
    remote:
      path: ToSic.Cre8magic.Client/Settings/MagicPackageSettings.cs
      branch: feature/cre8magic-tests
      repo: https://github.com/2sic/cre8magic.git
    id: Defaults
    path: ../ToSic.Cre8magic.Client/Settings/MagicPackageSettings.cs
    startLine: 13
  assemblies:
  - ToSic.Cre8Magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Client.Settings
  summary: >-
    All kinds of settings for the layout, how it should be etc.

    Should usually only serve as backup in case the JSON fails.
  example: []
  syntax:
    content: public MagicSettingsCatalog? Defaults { get; set; }
    parameters: []
    return:
      type: ToSic.Cre8magic.Client.Settings.MagicSettingsCatalog
    content.vb: Public Property Defaults As MagicSettingsCatalog
  overload: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.Defaults*
- uid: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.WwwRoot
  commentId: P:ToSic.Cre8magic.Client.Settings.MagicPackageSettings.WwwRoot
  id: WwwRoot
  parent: ToSic.Cre8magic.Client.Settings.MagicPackageSettings
  langs:
  - csharp
  - vb
  name: WwwRoot
  nameWithType: MagicPackageSettings.WwwRoot
  fullName: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.WwwRoot
  type: Property
  source:
    remote:
      path: ToSic.Cre8magic.Client/Settings/MagicPackageSettings.cs
      branch: feature/cre8magic-tests
      repo: https://github.com/2sic/cre8magic.git
    id: WwwRoot
    path: ../ToSic.Cre8magic.Client/Settings/MagicPackageSettings.cs
    startLine: 15
  assemblies:
  - ToSic.Cre8Magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Client.Settings
  syntax:
    content: public string WwwRoot { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property WwwRoot As String
  overload: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.WwwRoot*
- uid: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.SettingsJsonFile
  commentId: P:ToSic.Cre8magic.Client.Settings.MagicPackageSettings.SettingsJsonFile
  id: SettingsJsonFile
  parent: ToSic.Cre8magic.Client.Settings.MagicPackageSettings
  langs:
  - csharp
  - vb
  name: SettingsJsonFile
  nameWithType: MagicPackageSettings.SettingsJsonFile
  fullName: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.SettingsJsonFile
  type: Property
  source:
    remote:
      path: ToSic.Cre8magic.Client/Settings/MagicPackageSettings.cs
      branch: feature/cre8magic-tests
      repo: https://github.com/2sic/cre8magic.git
    id: SettingsJsonFile
    path: ../ToSic.Cre8magic.Client/Settings/MagicPackageSettings.cs
    startLine: 17
  assemblies:
  - ToSic.Cre8Magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Client.Settings
  syntax:
    content: public string SettingsJsonFile { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property SettingsJsonFile As String
  overload: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.SettingsJsonFile*
- uid: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.PackageName
  commentId: P:ToSic.Cre8magic.Client.Settings.MagicPackageSettings.PackageName
  id: PackageName
  parent: ToSic.Cre8magic.Client.Settings.MagicPackageSettings
  langs:
  - csharp
  - vb
  name: PackageName
  nameWithType: MagicPackageSettings.PackageName
  fullName: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.PackageName
  type: Property
  source:
    remote:
      path: ToSic.Cre8magic.Client/Settings/MagicPackageSettings.cs
      branch: feature/cre8magic-tests
      repo: https://github.com/2sic/cre8magic.git
    id: PackageName
    path: ../ToSic.Cre8magic.Client/Settings/MagicPackageSettings.cs
    startLine: 19
  assemblies:
  - ToSic.Cre8Magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Client.Settings
  syntax:
    content: public string PackageName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property PackageName As String
  overload: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.PackageName*
- uid: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.Url
  commentId: P:ToSic.Cre8magic.Client.Settings.MagicPackageSettings.Url
  id: Url
  parent: ToSic.Cre8magic.Client.Settings.MagicPackageSettings
  langs:
  - csharp
  - vb
  name: Url
  nameWithType: MagicPackageSettings.Url
  fullName: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.Url
  type: Property
  source:
    remote:
      path: ToSic.Cre8magic.Client/Settings/MagicPackageSettings.cs
      branch: feature/cre8magic-tests
      repo: https://github.com/2sic/cre8magic.git
    id: Url
    path: ../ToSic.Cre8magic.Client/Settings/MagicPackageSettings.cs
    startLine: 21
  assemblies:
  - ToSic.Cre8Magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Client.Settings
  syntax:
    content: public string Url { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Url As String
  overload: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.Url*
references:
- uid: ToSic.Cre8magic.Client.Settings
  commentId: N:ToSic.Cre8magic.Client.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Client.Settings
  nameWithType: ToSic.Cre8magic.Client.Settings
  fullName: ToSic.Cre8magic.Client.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Client
    name: Client
    href: ToSic.Cre8magic.Client.html
  - name: .
  - uid: ToSic.Cre8magic.Client.Settings
    name: Settings
    href: ToSic.Cre8magic.Client.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Client
    name: Client
    href: ToSic.Cre8magic.Client.html
  - name: .
  - uid: ToSic.Cre8magic.Client.Settings
    name: Settings
    href: ToSic.Cre8magic.Client.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.Defaults*
  commentId: Overload:ToSic.Cre8magic.Client.Settings.MagicPackageSettings.Defaults
  href: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.html#ToSic_Cre8magic_Client_Settings_MagicPackageSettings_Defaults
  name: Defaults
  nameWithType: MagicPackageSettings.Defaults
  fullName: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.Defaults
- uid: ToSic.Cre8magic.Client.Settings.MagicSettingsCatalog
  commentId: T:ToSic.Cre8magic.Client.Settings.MagicSettingsCatalog
  parent: ToSic.Cre8magic.Client.Settings
  href: ToSic.Cre8magic.Client.Settings.MagicSettingsCatalog.html
  name: MagicSettingsCatalog
  nameWithType: MagicSettingsCatalog
  fullName: ToSic.Cre8magic.Client.Settings.MagicSettingsCatalog
- uid: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.WwwRoot*
  commentId: Overload:ToSic.Cre8magic.Client.Settings.MagicPackageSettings.WwwRoot
  href: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.html#ToSic_Cre8magic_Client_Settings_MagicPackageSettings_WwwRoot
  name: WwwRoot
  nameWithType: MagicPackageSettings.WwwRoot
  fullName: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.WwwRoot
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.SettingsJsonFile*
  commentId: Overload:ToSic.Cre8magic.Client.Settings.MagicPackageSettings.SettingsJsonFile
  href: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.html#ToSic_Cre8magic_Client_Settings_MagicPackageSettings_SettingsJsonFile
  name: SettingsJsonFile
  nameWithType: MagicPackageSettings.SettingsJsonFile
  fullName: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.SettingsJsonFile
- uid: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.PackageName*
  commentId: Overload:ToSic.Cre8magic.Client.Settings.MagicPackageSettings.PackageName
  href: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.html#ToSic_Cre8magic_Client_Settings_MagicPackageSettings_PackageName
  name: PackageName
  nameWithType: MagicPackageSettings.PackageName
  fullName: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.PackageName
- uid: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.Url*
  commentId: Overload:ToSic.Cre8magic.Client.Settings.MagicPackageSettings.Url
  href: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.html#ToSic_Cre8magic_Client_Settings_MagicPackageSettings_Url
  name: Url
  nameWithType: MagicPackageSettings.Url
  fullName: ToSic.Cre8magic.Client.Settings.MagicPackageSettings.Url
