### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign
  commentId: T:ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign
  id: MagicBreadcrumbDesign
  parent: ToSic.Cre8magic.Client.Breadcrumbs.Settings
  children:
  - ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign.HasChildren
  - ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign.IsDisabled
  langs:
  - csharp
  - vb
  name: MagicBreadcrumbDesign
  nameWithType: MagicBreadcrumbDesign
  fullName: ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign
  type: Class
  source:
    remote:
      path: ToSic.Cre8magic.Client/Breadcrumbs/Settings/MagicBreadcrumbDesign.cs
      branch: feature/cre8magic-tests
      repo: https://github.com/2sic/cre8magic.git
    id: MagicBreadcrumbDesign
    path: ../ToSic.Cre8magic.Client/Breadcrumbs/Settings/MagicBreadcrumbDesign.cs
    startLine: 2
  assemblies:
  - ToSic.Cre8Magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Client.Breadcrumbs.Settings
  syntax:
    content: 'public class MagicBreadcrumbDesign : DesignSetting'
    content.vb: Public Class MagicBreadcrumbDesign Inherits DesignSetting
  inheritance:
  - System.Object
  - ToSic.Cre8magic.Client.Settings.DesignSetting
  inheritedMembers:
  - ToSic.Cre8magic.Client.Settings.DesignSetting.Classes
  - ToSic.Cre8magic.Client.Settings.DesignSetting.Value
  - ToSic.Cre8magic.Client.Settings.DesignSetting.Id
  - ToSic.Cre8magic.Client.Settings.DesignSetting.IsActive
  - ToSic.Cre8magic.Client.Settings.DesignSetting.IsPublished
  - ToSic.Cre8magic.Client.Settings.DesignSetting.IsAdmin
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign.HasChildren
  commentId: P:ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign.HasChildren
  id: HasChildren
  parent: ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign
  langs:
  - csharp
  - vb
  name: HasChildren
  nameWithType: MagicBreadcrumbDesign.HasChildren
  fullName: ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign.HasChildren
  type: Property
  source:
    remote:
      path: ToSic.Cre8magic.Client/Breadcrumbs/Settings/MagicBreadcrumbDesign.cs
      branch: feature/cre8magic-tests
      repo: https://github.com/2sic/cre8magic.git
    id: HasChildren
    path: ../ToSic.Cre8magic.Client/Breadcrumbs/Settings/MagicBreadcrumbDesign.cs
    startLine: 13
  assemblies:
  - ToSic.Cre8Magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Client.Breadcrumbs.Settings
  summary: Classes to add if this node is a parent (has-children).
  example: []
  syntax:
    content: public PairOnOff? HasChildren { get; set; }
    parameters: []
    return:
      type: ToSic.Cre8magic.Client.Settings.PairOnOff
    content.vb: Public Property HasChildren As PairOnOff
  overload: ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign.HasChildren*
- uid: ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign.IsDisabled
  commentId: P:ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign.IsDisabled
  id: IsDisabled
  parent: ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign
  langs:
  - csharp
  - vb
  name: IsDisabled
  nameWithType: MagicBreadcrumbDesign.IsDisabled
  fullName: ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign.IsDisabled
  type: Property
  source:
    remote:
      path: ToSic.Cre8magic.Client/Breadcrumbs/Settings/MagicBreadcrumbDesign.cs
      branch: feature/cre8magic-tests
      repo: https://github.com/2sic/cre8magic.git
    id: IsDisabled
    path: ../ToSic.Cre8magic.Client/Breadcrumbs/Settings/MagicBreadcrumbDesign.cs
    startLine: 19
  assemblies:
  - ToSic.Cre8Magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Client.Breadcrumbs.Settings
  summary: >-
    Classes to add if the node is disabled.

    TODO: unclear why it's disabled, what would cause this...
  example: []
  syntax:
    content: public PairOnOff? IsDisabled { get; set; }
    parameters: []
    return:
      type: ToSic.Cre8magic.Client.Settings.PairOnOff
    content.vb: Public Property IsDisabled As PairOnOff
  overload: ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign.IsDisabled*
references:
- uid: ToSic.Cre8magic.Client.Breadcrumbs.Settings
  commentId: N:ToSic.Cre8magic.Client.Breadcrumbs.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Client.Breadcrumbs.Settings
  nameWithType: ToSic.Cre8magic.Client.Breadcrumbs.Settings
  fullName: ToSic.Cre8magic.Client.Breadcrumbs.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Client
    name: Client
    href: ToSic.Cre8magic.Client.html
  - name: .
  - uid: ToSic.Cre8magic.Client.Breadcrumbs
    name: Breadcrumbs
    href: ToSic.Cre8magic.Client.Breadcrumbs.html
  - name: .
  - uid: ToSic.Cre8magic.Client.Breadcrumbs.Settings
    name: Settings
    href: ToSic.Cre8magic.Client.Breadcrumbs.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Client
    name: Client
    href: ToSic.Cre8magic.Client.html
  - name: .
  - uid: ToSic.Cre8magic.Client.Breadcrumbs
    name: Breadcrumbs
    href: ToSic.Cre8magic.Client.Breadcrumbs.html
  - name: .
  - uid: ToSic.Cre8magic.Client.Breadcrumbs.Settings
    name: Settings
    href: ToSic.Cre8magic.Client.Breadcrumbs.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: ToSic.Cre8magic.Client.Settings.DesignSetting
  commentId: T:ToSic.Cre8magic.Client.Settings.DesignSetting
  parent: ToSic.Cre8magic.Client.Settings
  href: ToSic.Cre8magic.Client.Settings.DesignSetting.html
  name: DesignSetting
  nameWithType: DesignSetting
  fullName: ToSic.Cre8magic.Client.Settings.DesignSetting
- uid: ToSic.Cre8magic.Client.Settings.DesignSetting.Classes
  commentId: P:ToSic.Cre8magic.Client.Settings.DesignSetting.Classes
  parent: ToSic.Cre8magic.Client.Settings.DesignSetting
  href: ToSic.Cre8magic.Client.Settings.DesignSetting.html#ToSic_Cre8magic_Client_Settings_DesignSetting_Classes
  name: Classes
  nameWithType: DesignSetting.Classes
  fullName: ToSic.Cre8magic.Client.Settings.DesignSetting.Classes
- uid: ToSic.Cre8magic.Client.Settings.DesignSetting.Value
  commentId: P:ToSic.Cre8magic.Client.Settings.DesignSetting.Value
  parent: ToSic.Cre8magic.Client.Settings.DesignSetting
  href: ToSic.Cre8magic.Client.Settings.DesignSetting.html#ToSic_Cre8magic_Client_Settings_DesignSetting_Value
  name: Value
  nameWithType: DesignSetting.Value
  fullName: ToSic.Cre8magic.Client.Settings.DesignSetting.Value
- uid: ToSic.Cre8magic.Client.Settings.DesignSetting.Id
  commentId: P:ToSic.Cre8magic.Client.Settings.DesignSetting.Id
  parent: ToSic.Cre8magic.Client.Settings.DesignSetting
  href: ToSic.Cre8magic.Client.Settings.DesignSetting.html#ToSic_Cre8magic_Client_Settings_DesignSetting_Id
  name: Id
  nameWithType: DesignSetting.Id
  fullName: ToSic.Cre8magic.Client.Settings.DesignSetting.Id
- uid: ToSic.Cre8magic.Client.Settings.DesignSetting.IsActive
  commentId: P:ToSic.Cre8magic.Client.Settings.DesignSetting.IsActive
  parent: ToSic.Cre8magic.Client.Settings.DesignSetting
  href: ToSic.Cre8magic.Client.Settings.DesignSetting.html#ToSic_Cre8magic_Client_Settings_DesignSetting_IsActive
  name: IsActive
  nameWithType: DesignSetting.IsActive
  fullName: ToSic.Cre8magic.Client.Settings.DesignSetting.IsActive
- uid: ToSic.Cre8magic.Client.Settings.DesignSetting.IsPublished
  commentId: P:ToSic.Cre8magic.Client.Settings.DesignSetting.IsPublished
  parent: ToSic.Cre8magic.Client.Settings.DesignSetting
  href: ToSic.Cre8magic.Client.Settings.DesignSetting.html#ToSic_Cre8magic_Client_Settings_DesignSetting_IsPublished
  name: IsPublished
  nameWithType: DesignSetting.IsPublished
  fullName: ToSic.Cre8magic.Client.Settings.DesignSetting.IsPublished
- uid: ToSic.Cre8magic.Client.Settings.DesignSetting.IsAdmin
  commentId: P:ToSic.Cre8magic.Client.Settings.DesignSetting.IsAdmin
  parent: ToSic.Cre8magic.Client.Settings.DesignSetting
  href: ToSic.Cre8magic.Client.Settings.DesignSetting.html#ToSic_Cre8magic_Client_Settings_DesignSetting_IsAdmin
  name: IsAdmin
  nameWithType: DesignSetting.IsAdmin
  fullName: ToSic.Cre8magic.Client.Settings.DesignSetting.IsAdmin
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Client.Settings
  commentId: N:ToSic.Cre8magic.Client.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Client.Settings
  nameWithType: ToSic.Cre8magic.Client.Settings
  fullName: ToSic.Cre8magic.Client.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Client
    name: Client
    href: ToSic.Cre8magic.Client.html
  - name: .
  - uid: ToSic.Cre8magic.Client.Settings
    name: Settings
    href: ToSic.Cre8magic.Client.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Client
    name: Client
    href: ToSic.Cre8magic.Client.html
  - name: .
  - uid: ToSic.Cre8magic.Client.Settings
    name: Settings
    href: ToSic.Cre8magic.Client.Settings.html
- uid: ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign.HasChildren*
  commentId: Overload:ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign.HasChildren
  href: ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign.html#ToSic_Cre8magic_Client_Breadcrumbs_Settings_MagicBreadcrumbDesign_HasChildren
  name: HasChildren
  nameWithType: MagicBreadcrumbDesign.HasChildren
  fullName: ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign.HasChildren
- uid: ToSic.Cre8magic.Client.Settings.PairOnOff
  commentId: T:ToSic.Cre8magic.Client.Settings.PairOnOff
  parent: ToSic.Cre8magic.Client.Settings
  href: ToSic.Cre8magic.Client.Settings.PairOnOff.html
  name: PairOnOff
  nameWithType: PairOnOff
  fullName: ToSic.Cre8magic.Client.Settings.PairOnOff
- uid: ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign.IsDisabled*
  commentId: Overload:ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign.IsDisabled
  href: ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign.html#ToSic_Cre8magic_Client_Breadcrumbs_Settings_MagicBreadcrumbDesign_IsDisabled
  name: IsDisabled
  nameWithType: MagicBreadcrumbDesign.IsDisabled
  fullName: ToSic.Cre8magic.Client.Breadcrumbs.Settings.MagicBreadcrumbDesign.IsDisabled
