### YamlMime:ManagedReference
items:
- uid: ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions
  commentId: T:ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions
  id: IHasSettingsExceptions
  parent: ToSic.Cre8magic.Client.Settings
  children:
  - ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions.Exceptions
  - ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions.HasExceptions
  langs:
  - csharp
  - vb
  name: IHasSettingsExceptions
  nameWithType: IHasSettingsExceptions
  fullName: ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions
  type: Interface
  source:
    remote:
      path: ToSic.Cre8magic.Client/Settings/IHasSettingsExceptions.cs
      branch: feature/cre8magic-tests
      repo: https://github.com/2sic/cre8magic.git
    id: IHasSettingsExceptions
    path: ../ToSic.Cre8magic.Client/Settings/IHasSettingsExceptions.cs
    startLine: 2
  assemblies:
  - ToSic.Cre8Magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Client.Settings
  syntax:
    content: public interface IHasSettingsExceptions
    content.vb: Public Interface IHasSettingsExceptions
- uid: ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions.HasExceptions
  commentId: P:ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions.HasExceptions
  id: HasExceptions
  parent: ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions
  langs:
  - csharp
  - vb
  name: HasExceptions
  nameWithType: IHasSettingsExceptions.HasExceptions
  fullName: ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions.HasExceptions
  type: Property
  source:
    remote:
      path: ToSic.Cre8magic.Client/Settings/IHasSettingsExceptions.cs
      branch: feature/cre8magic-tests
      repo: https://github.com/2sic/cre8magic.git
    id: HasExceptions
    path: ../ToSic.Cre8magic.Client/Settings/IHasSettingsExceptions.cs
    startLine: 4
  assemblies:
  - ToSic.Cre8Magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Client.Settings
  syntax:
    content: bool HasExceptions { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property HasExceptions As Boolean
  overload: ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions.HasExceptions*
- uid: ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions.Exceptions
  commentId: P:ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions.Exceptions
  id: Exceptions
  parent: ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions
  langs:
  - csharp
  - vb
  name: Exceptions
  nameWithType: IHasSettingsExceptions.Exceptions
  fullName: ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions.Exceptions
  type: Property
  source:
    remote:
      path: ToSic.Cre8magic.Client/Settings/IHasSettingsExceptions.cs
      branch: feature/cre8magic-tests
      repo: https://github.com/2sic/cre8magic.git
    id: Exceptions
    path: ../ToSic.Cre8magic.Client/Settings/IHasSettingsExceptions.cs
    startLine: 6
  assemblies:
  - ToSic.Cre8Magic.Client.Oqtane
  namespace: ToSic.Cre8magic.Client.Settings
  syntax:
    content: List<Exception> Exceptions { get; }
    parameters: []
    return:
      type: System.Collections.Generic.List{System.Exception}
    content.vb: ReadOnly Property Exceptions As List(Of Exception)
  overload: ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions.Exceptions*
references:
- uid: ToSic.Cre8magic.Client.Settings
  commentId: N:ToSic.Cre8magic.Client.Settings
  href: ToSic.html
  name: ToSic.Cre8magic.Client.Settings
  nameWithType: ToSic.Cre8magic.Client.Settings
  fullName: ToSic.Cre8magic.Client.Settings
  spec.csharp:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Client
    name: Client
    href: ToSic.Cre8magic.Client.html
  - name: .
  - uid: ToSic.Cre8magic.Client.Settings
    name: Settings
    href: ToSic.Cre8magic.Client.Settings.html
  spec.vb:
  - uid: ToSic
    name: ToSic
    href: ToSic.html
  - name: .
  - uid: ToSic.Cre8magic
    name: Cre8magic
    href: ToSic.Cre8magic.html
  - name: .
  - uid: ToSic.Cre8magic.Client
    name: Client
    href: ToSic.Cre8magic.Client.html
  - name: .
  - uid: ToSic.Cre8magic.Client.Settings
    name: Settings
    href: ToSic.Cre8magic.Client.Settings.html
- uid: ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions.HasExceptions*
  commentId: Overload:ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions.HasExceptions
  href: ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions.html#ToSic_Cre8magic_Client_Settings_IHasSettingsExceptions_HasExceptions
  name: HasExceptions
  nameWithType: IHasSettingsExceptions.HasExceptions
  fullName: ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions.HasExceptions
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions.Exceptions*
  commentId: Overload:ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions.Exceptions
  href: ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions.html#ToSic_Cre8magic_Client_Settings_IHasSettingsExceptions_Exceptions
  name: Exceptions
  nameWithType: IHasSettingsExceptions.Exceptions
  fullName: ToSic.Cre8magic.Client.Settings.IHasSettingsExceptions.Exceptions
- uid: System.Collections.Generic.List{System.Exception}
  commentId: T:System.Collections.Generic.List{System.Exception}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<Exception>
  nameWithType: List<Exception>
  fullName: System.Collections.Generic.List<System.Exception>
  nameWithType.vb: List(Of Exception)
  fullName.vb: System.Collections.Generic.List(Of System.Exception)
  name.vb: List(Of Exception)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: System.Exception
    name: Exception
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.exception
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.Exception
    name: Exception
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.exception
  - name: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
